Named arguments for `entry.py`
OpenFn/apollo pull request #135
Opened 2024-12-12 16:08 UTC by elias-ba

## Short Description

Refactor Python service entry point to use named arguments instead of positional arguments, making it more maintainable and less prone to errors.

Fixes #132 

## Implementation Details

The Python service entry point (entry.py) is a critical piece of infrastructure used by both the API at runtime and local development commands like `bun py`. Previously, it relied on positional arguments (4 or 5 depending on context) to determine service configuration, which was causing maintainability issues and potential confusion.

Changes made:
1. Replace positional arguments with named arguments using argparse:
   ```python
   python services/entry.py --service echo --input input.json --output output.json
   ```

    - --service (-s): Name of the service to run
    - --input (-i): Path to input JSON file
    - --output (-o): Path to output JSON file (auto-generated if not provided)
    - --port (-p): Apollo server port
   
2. Add proper error handling:

    - Invalid JSON input now returns a status code 500 with descriptive error message
    - Added type hints for better code clarity

3. Updated `bridge.ts` to use the new argument format when spawning Python processes

The interface is now more explicit and self-documenting, while maintaining backward compatibility at the API level.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

2024-12-12 17:59 UTC, josephjclark commented
Thank you so much @elias-ba ! I look forward to reviewing this tomorrow

2024-12-13 11:56 UTC, josephjclark requested changes
Thanks @elias-ba! This seems to work great. One request please, then I'll ask Hanna to test (this works great with the assistant though)

One question: how do we use `entry_test.py`?

2024-12-13 11:56 UTC, josephjclark commented on platform/src/bridge.ts
> +        "--service",
Can we make script name required and position? I think the absolute minimum here is `python services/entry.py <service>`, and everything else is probably technically optional (even if we usually use it)

2024-12-13 15:17 UTC, elias-ba commented
Thanks for the review, @josephjclark! 🙌 

I’ve implemented the changes you requested, so everything should be good to go now. Let me know if there’s anything else you’d like adjusted.

You can run the `services/entry_test.py` using `pytest` like this:

```bash
pytest services/entry_test.py
```

I have updated the `pyproject.toml`file at the root of the project to include `pytest`. It's a cool little package for writing and running unit tests in Python. So you may probably need to install it by running `poetry install` before:

Let me know if you hit any snags or need help with it! Appreciate your feedback, as always! ✌️

2024-12-13 17:47 UTC, josephjclark commented
Thank you @elias-ba :pray: 

@hanna-paasivirta when you're next online:

Remember that change you made to the arg parser in https://github.com/OpenFn/apollo/pull/131/commits/b383b0d4364855689a501f2a16037f639a68008d ?

Could you repeat your test to expose that? It'll fail on main now but should work against this branch. If you have trouble please let me know ASAP. Thanks!

2024-12-16 13:54 UTC, hanna-paasivirta commented
@josephjclark It seems to work fine now. I modified the example command in embeddings demo to match the new named arguments.

2024-12-16 14:11 UTC, josephjclark commented
Great catch @hanna-paasivirta , thank you!

2024-12-16 14:11 UTC, merged